[Interface]
Address = 10.0.0.2/24
PrivateKey = ACatqUC7diI0F5bQu5/5NGDbl0mQSbd7lsJIye9kYH4=
SaveConfig = false
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = a7t+jzOb7pGa9X1P/9zrtkwSVSOJsqOdVE77mRN6lyA=
Endpoint = 179.209.143.160:51820
AllowedIPs = 10.0.0.0/24, 127.0.0.1/32
PersistentKeepalive = 25
