server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        format_sql: true

ollama:
  url: ${OLLAMA_URL:http://localhost:11434}
  model: ${OLLAMA_MODEL:qwen2.5-coder:7b}

logging:
  level:
    root: INFO
    com.alexai: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always